trigger:
- main

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM - TestEnvironment
  environment:
   name: TestEnvironment
   resourceType: virtualMachine
   tags: frontend
  strategy:
     runOnce:
        deploy:
          steps:
            - checkout: self
            - script: docker compose build
            - script: docker compose up -d